[package]
name = "angelina"
version = "0.0.1"
authors = ["tfiasco <fiasco.t.19@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sled = "0.33.0"
bytes = "0.5.6"
strum = "0.18.0"
strum_macros = "0.18.0"
